server:
  port: 8888

logging:
  level:
    ROOT: DEBUG
    org.spring.framework.cloud.config: DEBUG

management:
  endpoint:
    health:
      show-details: always

# bootstrap.yml
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ju-bari/event-driven-msa-practice-config
          username: Ju-bari
          password: ENC(SwxK+99yTpYz8vVrOIyVnQTuZ8oSjss9mM4sL23tDehNzWMAhzGxpjL2ByK79htuLthQo3uL8DOUp/pCQ/Q9JYt/0rzpgI8929k2ksC8zHKJfpYeZdCWhh5kIcYO5cPxkqgdyZoVlE3GP37sY7f2nsXdFGkgZES1HdzFJZZjby8=)
          default-label: master
        encrypt:
          enabled: true
    fail-fast: true
  security:
    user:
      name: spring_cloud_user
      password: ENC(O8Tpi+WLMRESfRbxgswfuE9VaXdTOjQs+EH6HL0K7LYwrprUrCSiJoTKOK/VWe0F)

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
    algorithm: PBEWITHHMACSHA512ANDAES_256
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator


#spring:
#  application:
#    name: configserver
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/Ju-bari/event-driven-msa-practice
#          search-paths: config-server-repository/**
#          username: Ju-bari
#          password:
#          clone-on-start: true
#          default-label: master
#     fail-fast: true