server:
  port: 8888

logging:
  level:
    ROOT: DEBUG
    org.spring.framework.cloud.config: DEBUG

management:
  endpoint:
    health:
      show-details: always

# bootstrap.yml
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ju-bari/event-driven-msa-practice-config
          username: Ju-bari
          password: ENC(N8Co5uuPhU7BdKkhSZm8hKBMgStezJU/EHEMi/Os8mh2D2xA5gifEYPPdo65HRT42wDqyxJ1qFK4tVPj5Pu2AtW0eqXTup7/p2Bgd/EB0gbSXmx6cfz9lf9xl40Ir8ybff2Jw76VobHPvjZ+argrGHyE69RWzwUHFAiEVZU0D+Q=)
          default-label: master
        encrypt:
          enabled: true
    fail-fast: true
  security:
    user:
      name: spring_cloud_user
      password: ENC(9quWSc/wS8R0ZWEvCl/c/du9nj1/rizPw3t2pq4imyfDtLarE10oO/vdfbAFsqKg)

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
    algorithm: PBEWITHHMACSHA512ANDAES_256
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator


#spring:
#  application:
#    name: configserver
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/Ju-bari/event-driven-msa-practice
#          search-paths: config-server-repository/**
#          username: Ju-bari
#          password:
#          clone-on-start: true
#          default-label: master
#     fail-fast: true